title = "Infinite Scribe Gitleaks Config"

[extend]
useDefault = true

[allowlist]
paths = [
    '''\.env\.example''',
    '''\.env\.template''',
    '''\.env\.test''',
    '''test_.*\.py''',
    '''.*_test\.py''',
    '''.*\.md''',
    '''CLAUDE\.md''',
    '''\.trivyignore''',
    '''\.gitleaks\.toml''',
    '''apps/backend/tests/.*''',
]

regexes = [
    '''devPostgres123''',
    '''devNeo4j123''',
    '''devRedis123''',
    '''your_.*_key''',
    '''example_.*_key''',
    '''test.*password''',
    '''192\.168\.\d+\.\d+''',
]