# Pre-commit hooks for code quality
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Python formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      # Run ruff linter
      - id: ruff
        args: [--fix]
        files: ^apps/backend/
      # Run ruff formatter (replaces black)
      - id: ruff-format
        files: ^apps/backend/

  # Additional Python checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: debug-statements
        files: ^apps/backend/.*\.py$
      - id: mixed-line-ending
        args: [--fix=lf]

  # Python security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, pyproject.toml, -r, apps/backend/src/]
        additional_dependencies: ['bandit[toml]']

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^apps/backend/src/
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies:
          - types-redis
          - types-pyyaml

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown]
        exclude: ^(docs/.*\.md|.*\.yml)$

  # Docker linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile$

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        files: \.(sh|bash)$

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: ^(CHANGELOG\.md|docs/.*\.md)$

# Configuration for specific hooks
default_language_version:
  python: python3.11

# Run hooks only on changed files
fail_fast: false

# Exclude directories
exclude: |
  (?x)^(
    \.git/|
    \.venv/|
    venv/|
    __pycache__/|
    \.pytest_cache/|
    \.mypy_cache/|
    node_modules/|
    build/|
    dist/|
    \.next/|
    coverage/|
    htmlcov/|
    data/|
    logs/|
    tmp/|
    \.DS_Store
  )
