[project]
name = "infinite-scribe-backend"
version = "0.1.0"
description = "Infinite Scribe Backend - API Gateway and Agent Services"
requires-python = ">=3.11"

dependencies = [
    # Core Web Framework
    "fastapi~=0.115.13",
    "pydantic~=2.11.7",
    "pydantic-settings~=2.6.0",
    "uvicorn[standard]~=0.32.0",
    
    # Databases
    "asyncpg~=0.30.0",
    "neo4j~=5.26.0", 
    "redis~=5.2.0",
    "pymilvus~=2.4.9",
    
    # AI/ML Providers
    "openai~=1.54.0",
    "anthropic~=0.39.0",
    "litellm~=1.52.0",
    "langfuse~=2.57.0",
    
    # Infrastructure
    "aiokafka~=0.11.0",
    "prefect~=2.19.0",
    "minio~=7.2.10",
    
    # Utilities
    "python-dotenv~=1.0.1",
    "structlog~=24.4.0",
    "httpx~=0.27.0",
    "tenacity~=9.0.0",
    "pyyaml~=6.0.2",
]

[project.optional-dependencies]
dev = [
    # Testing
    "pytest~=8.3.3",
    "pytest-asyncio~=0.24.0",
    "pytest-cov~=6.0.0",
    "pytest-mock~=3.14.0",
    
    # Code Quality
    "ruff~=0.7.2",
    "black~=24.10.0",
    "mypy~=1.13.0",
    
    # Development Tools
    "ipdb~=0.13.13",
    "rich~=13.9.2",
    "watchdog~=6.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Entry points for different services
[project.scripts]
api-gateway = "src.api.main:run"
agent-worldsmith = "src.agents.worldsmith.main:run"
agent-plotmaster = "src.agents.plotmaster.main:run"
agent-outliner = "src.agents.outliner.main:run"
agent-director = "src.agents.director.main:run"
agent-characterexpert = "src.agents.characterexpert.main:run"
agent-worldbuilder = "src.agents.worldbuilder.main:run"
agent-writer = "src.agents.writer.main:run"
agent-critic = "src.agents.critic.main:run"
agent-factchecker = "src.agents.factchecker.main:run"
agent-rewriter = "src.agents.rewriter.main:run"