version: '3.8'

services:
  maildev:
    image: maildev/maildev:latest
    container_name: e2e-maildev
    ports:
      - "1025:1025"  # SMTP 端口
      - "1080:1080"  # Web UI 端口
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_USER=${MAILDEV_WEB_USER:-}
      - MAILDEV_WEB_PASS=${MAILDEV_WEB_PASS:-}
      - MAILDEV_INCOMING_USER=${MAILDEV_INCOMING_USER:-}
      - MAILDEV_INCOMING_PASS=${MAILDEV_INCOMING_PASS:-}
    command: >
      maildev
      --web 1080
      --smtp 1025
      --hide-extensions STARTTLS
    restart: unless-stopped
    networks:
      - e2e-test

  # 可选：添加一个简单的健康检查服务
  maildev-healthcheck:
    image: curlimages/curl:latest
    depends_on:
      - maildev
    command: >
      sh -c "
        echo 'Waiting for MailDev to start...'
        until curl -f http://maildev:1080/ > /dev/null 2>&1; do
          echo 'MailDev not ready yet, waiting...'
          sleep 2
        done
        echo 'MailDev is ready!'
        echo 'Web UI: http://localhost:1080'
        echo 'SMTP: localhost:1025'
      "
    networks:
      - e2e-test

networks:
  e2e-test:
    driver: bridge